import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

// NB https://github.com/vercel/next.js/discussions/58693#discussioncomment-8024154
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'KK Tech Test',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>{children}</body>
    </html>
  );
}
